/**:
  ros__parameters:
    camera_info_url: package://rm_bringup/config/camera_info.yaml
    exposure_time: 3000
    analog_gain: 10
    gamma: 100
    rgb_gain.r: 152
    rgb_gain.g: 125
    rgb_gain.b: 100
    camera_name: "mv_camera"
    recording: false    #是否录制

